### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by andorfermichael** [cdimascio/dbpedia-sparql-client#1]
When I use the code from the documentation I get the following error: 

Uncaught TypeError: _npmDbpediaSparqlClient.default.client is not a function

Any solution for that?

**Comment by cdimascio** [comment]
i am not able to repro this issue on version 0.8.6.
can you verify that you are using the es5 example with es5 and/or the es6 example with es6?
please paste the code you are using. i will run that as well in attempt to repro

**Comment by andorfermichael** [comment]
I have added you to the project as a collaborator  (I have to keep it private for now). Clone it and run "npm install" plus "bower install". Afterwards run the web application with "ember s" and then press the start button on the homepage. In the console you will see the error. The error causing code is located in app/components/cesium-widget.js

**Comment by cdimascio** [comment]
Hi
I loaded up your code and was able to repro the issue. Thanks!
I had to make some adjustments to enable dbpedia-sparl-client to work in
the browser. It was previously written to work only in the Node runtime.

All in all, I have it working with your code base.

Here is what to do:
Upgrade dbpedia-sparql-client to the latest i.e. 0.9.1

in cesium-widget.js, import the module as follows:

import dp from 'npm:dbpedia-sparql-client';
const dps = dp.default;

Note, the second line, dp.default. At the moment, this is necessary. There
seems to be some interference with module loader. I need to look into it a
bit more. I'm not sure if the problem is on my end or if it has to do with
the loader and/or loader config. All in all, it will work with the above
code.

Let me know how it goes,

Thanks for the issue submission.

-carmine

**Comment by andorfermichael** [comment]
Hi Carmine

Everything works as expected now. 

Thank you very much for your quick response and reaction. 

I think it is really nice to be able to use your helpful and modern module not only in the node environment but also in the browser.

By the way, you have a typo in your README.md "npm install dbpedi**q**-sparql-client". The q has to be an a. :)

Again thank you very much. :+1:

**Comment by cdimascio** [comment]
Sure thing. I'll update the README as well. Thanks!
